//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstoqueClient.IServicoEstoque1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/EstoqueLibrary")]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescricaoProdutoField;
        
        private int EstoqueProdutoField;
        
        private string NomeProdutoField;
        
        private string NumeroProdutoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoProduto
        {
            get
            {
                return this.DescricaoProdutoField;
            }
            set
            {
                this.DescricaoProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstoqueProduto
        {
            get
            {
                return this.EstoqueProdutoField;
            }
            set
            {
                this.EstoqueProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto
        {
            get
            {
                return this.NomeProdutoField;
            }
            set
            {
                this.NomeProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProduto
        {
            get
            {
                return this.NumeroProdutoField;
            }
            set
            {
                this.NumeroProdutoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/01", ConfigurationName="EstoqueClient.IServicoEstoque1.IServicoEstoque1")]
    public interface IServicoEstoque1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/ListarProdutos", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/ListarProdutosResponse")]
        string[] ListarProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/ListarProdutos", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/ListarProdutosResponse")]
        System.Threading.Tasks.Task<string[]> ListarProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/IncluirProduto", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/IncluirProdutoResponse")]
        bool IncluirProduto(EstoqueClient.IServicoEstoque1.Produto Produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/IncluirProduto", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/IncluirProdutoResponse")]
        System.Threading.Tasks.Task<bool> IncluirProdutoAsync(EstoqueClient.IServicoEstoque1.Produto Produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverProduto", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverProdutoResponse")]
        bool RemoverProduto(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverProduto", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverProdutoResponse")]
        System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/ConsultaEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/ConsultaEstoqueResponse")]
        int ConsultaEstoque(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/ConsultaEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/ConsultaEstoqueResponse")]
        System.Threading.Tasks.Task<int> ConsultaEstoqueAsync(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/AdicionarEstoqueResponse")]
        bool AdicionarEstoque(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/AdicionarEstoqueResponse")]
        System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverEstoqueResponse")]
        bool RemoverEstoque(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/RemoverEstoqueResponse")]
        System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string NumeroProduto, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/VerProduto", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/VerProdutoResponse")]
        EstoqueClient.IServicoEstoque1.Produto VerProduto(string NumeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IServicoEstoque1/VerProduto", ReplyAction="http://projetoavaliativo.dm113/01/IServicoEstoque1/VerProdutoResponse")]
        System.Threading.Tasks.Task<EstoqueClient.IServicoEstoque1.Produto> VerProdutoAsync(string NumeroProduto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoEstoque1Channel : EstoqueClient.IServicoEstoque1.IServicoEstoque1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoEstoque1Client : System.ServiceModel.ClientBase<EstoqueClient.IServicoEstoque1.IServicoEstoque1>, EstoqueClient.IServicoEstoque1.IServicoEstoque1
    {
        
        public ServicoEstoque1Client()
        {
        }
        
        public ServicoEstoque1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ServicoEstoque1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ServicoEstoque1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ServicoEstoque1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string[] ListarProdutos()
        {
            return base.Channel.ListarProdutos();
        }
        
        public System.Threading.Tasks.Task<string[]> ListarProdutosAsync()
        {
            return base.Channel.ListarProdutosAsync();
        }
        
        public bool IncluirProduto(EstoqueClient.IServicoEstoque1.Produto Produto)
        {
            return base.Channel.IncluirProduto(Produto);
        }
        
        public System.Threading.Tasks.Task<bool> IncluirProdutoAsync(EstoqueClient.IServicoEstoque1.Produto Produto)
        {
            return base.Channel.IncluirProdutoAsync(Produto);
        }
        
        public bool RemoverProduto(string NumeroProduto)
        {
            return base.Channel.RemoverProduto(NumeroProduto);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string NumeroProduto)
        {
            return base.Channel.RemoverProdutoAsync(NumeroProduto);
        }
        
        public int ConsultaEstoque(string NumeroProduto)
        {
            return base.Channel.ConsultaEstoque(NumeroProduto);
        }
        
        public System.Threading.Tasks.Task<int> ConsultaEstoqueAsync(string NumeroProduto)
        {
            return base.Channel.ConsultaEstoqueAsync(NumeroProduto);
        }
        
        public bool AdicionarEstoque(string NumeroProduto, int Quantidade)
        {
            return base.Channel.AdicionarEstoque(NumeroProduto, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string NumeroProduto, int Quantidade)
        {
            return base.Channel.AdicionarEstoqueAsync(NumeroProduto, Quantidade);
        }
        
        public bool RemoverEstoque(string NumeroProduto, int Quantidade)
        {
            return base.Channel.RemoverEstoque(NumeroProduto, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string NumeroProduto, int Quantidade)
        {
            return base.Channel.RemoverEstoqueAsync(NumeroProduto, Quantidade);
        }
        
        public EstoqueClient.IServicoEstoque1.Produto VerProduto(string NumeroProduto)
        {
            return base.Channel.VerProduto(NumeroProduto);
        }
        
        public System.Threading.Tasks.Task<EstoqueClient.IServicoEstoque1.Produto> VerProdutoAsync(string NumeroProduto)
        {
            return base.Channel.VerProdutoAsync(NumeroProduto);
        }
    }
}
